#include "RefDB.h"
#include "print.h"
#include "bit_convert.h"
#include <cstring>

using namespace std;

int main() {
	RefDB db;
	db.init_generate();
	char chromo1[] = "ACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTGACTG";
	char chromo2[] = "GGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCCGGCC";

	db.add_chromo(chromo1, 512);
	db.add_chromo(chromo2, 512);

	db.finish_and_store("test");

	db.init_load("test");
	db.load_chromo(1);

	__m256i bit0;
	__m256i bit1;

	db.query(1, 13, 256, bit0, bit1);

	print256_bit(bit0);
	print256_bit(bit1);

	char str_buffer [256] __aligned__;
	uint8_t bit0_buffer [32] __aligned__;
	uint8_t bit1_buffer [32] __aligned__;

	memcpy(str_buffer, chromo2 + 13, 256);
	avx_convert2bit(str_buffer, bit0_buffer, bit1_buffer);

	__m256i *bit0_ptr = (__m256i*) bit0_buffer;
	__m256i *bit1_ptr = (__m256i*) bit1_buffer;

	print256_bit(*bit0_ptr);
	print256_bit(*bit1_ptr);

	return 0;
}
